import jsPDF from "jspdf";
import type { BrandingParam } from "./pdf-receipts";

// Primary Green: #1B4332 | Secondary Green: #2D6A4F
const PRIMARY_GREEN = [27, 67, 50] as const;
const SECONDARY_GREEN = [45, 106, 79] as const;
const PALE_MINT = [216, 243, 220] as const;

function formatCurrencyPlain(amount: number, currency: string = "UGX"): string {
  const locale = currency === "USD" ? "en-US" : "en-UG";
  const formatter = new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: currency === "USD" ? 2 : 0,
    maximumFractionDigits: currency === "USD" ? 2 : 0,
  });
  return formatter.format(amount);
}

function addHeader(doc: jsPDF, branding?: BrandingParam): number {
  const schoolName = branding?.schoolName || "HelioPay System";
  const schoolAddress = branding?.schoolAddress || "";
  const logoUrl = branding?.logoUrl;
  const hasLogo = logoUrl && logoUrl.startsWith("data:");
  const headerHeight = schoolAddress ? 48 : 42;

  doc.setFillColor(...PRIMARY_GREEN);
  doc.rect(0, 0, 210, headerHeight, "F");

  if (hasLogo) {
    try {
      const logoSize = 28;
      const logoX = 12;
      const logoY = (headerHeight - logoSize) / 2;
      doc.addImage(logoUrl, "PNG", logoX, logoY, logoSize, logoSize);
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text(schoolName, 50, schoolAddress ? 16 : 20);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      if (schoolAddress) {
        doc.text(schoolAddress, 50, 25);
        doc.text("Financial Report", 50, 34);
      } else {
        doc.text("Financial Report", 50, 28);
      }
    } catch {
      _renderTextHeader(doc, schoolName, schoolAddress, headerHeight, "Financial Report");
    }
  } else {
    _renderTextHeader(doc, schoolName, schoolAddress, headerHeight, "Financial Report");
  }

  doc.setTextColor(0, 0, 0);
  return headerHeight + 10;
}

function _renderTextHeader(doc: jsPDF, schoolName: string, schoolAddress: string, headerHeight: number, subtitle: string): void {
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(schoolName, 105, schoolAddress ? 17 : 19, { align: "center" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  if (schoolAddress) {
    doc.text(schoolAddress, 105, 27, { align: "center" });
    doc.text(subtitle, 105, 35, { align: "center" });
  } else {
    doc.text(subtitle, 105, 28, { align: "center" });
  }
}

function addLine(doc: jsPDF, y: number): number {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);
  return y + 6;
}

function addTableHeader(doc: jsPDF, y: number, cols: { label: string; x: number; align?: "right" | "center" }[]): number {
  doc.setFillColor(...PRIMARY_GREEN);
  doc.rect(20, y, 170, 9, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  cols.forEach(c => {
    if (c.align === "right") {
      doc.text(c.label, c.x, y + 6, { align: "right" });
    } else {
      doc.text(c.label, c.x, y + 6);
    }
  });
  return y + 13;
}

function addFooter(doc: jsPDF, branding?: BrandingParam): void {
  const schoolName = branding?.schoolName || "HelioPay System";
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(`Generated by ${schoolName} on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 105, pageHeight - 8, { align: "center" });
}

// ─── Financial Summary Report ───────────────────────────────────────────────

export interface FinancialSummary {
  totalIncome: { UGX: number; USD: number };
  totalExpenses: { UGX: number; USD: number };
  netBalance: { UGX: number; USD: number };
  expensesByCategory: { category: string; amount: number; currency: string }[];
  incomeByFeeType: { feeType: string; amount: number; currency: string }[];
  period: string;
  startDate: string;
  endDate: string;
}

export function generateFinancialReportPDF(data: FinancialSummary, branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const periodLabel = data.period === "weekly" ? "Weekly" : data.period === "monthly" ? "Monthly" : "Termly";
  doc.text(`${periodLabel} Financial Report`, 105, y, { align: "center" });
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const start = new Date(data.startDate).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  const end = new Date(data.endDate).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  doc.text(`Period: ${start} - ${end}`, 105, y, { align: "center" });
  y += 10;

  y = addLine(doc, y);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Financial Summary", 20, y);
  y += 10;

  const colLeft = 20;
  const colRight = 110;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Income (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text(formatCurrencyPlain(data.totalIncome.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Income (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text(formatCurrencyPlain(data.totalIncome.USD, "USD"), colRight, y + 5);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Expenses (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text(formatCurrencyPlain(data.totalExpenses.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Expenses (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text(formatCurrencyPlain(data.totalExpenses.USD, "USD"), colRight, y + 5);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Net Balance (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(data.netBalance.UGX >= 0 ? 22 : 220, data.netBalance.UGX >= 0 ? 163 : 38, data.netBalance.UGX >= 0 ? 74 : 38);
  doc.text(formatCurrencyPlain(data.netBalance.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Net Balance (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(data.netBalance.USD >= 0 ? 22 : 220, data.netBalance.USD >= 0 ? 163 : 38, data.netBalance.USD >= 0 ? 74 : 38);
  doc.text(formatCurrencyPlain(data.netBalance.USD, "USD"), colRight, y + 5);
  y += 16;

  y = addLine(doc, y);

  if (data.incomeByFeeType.length > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY_GREEN);
    doc.text("Income by Fee Type", 20, y);
    y += 8;

    y = addTableHeader(doc, y, [
      { label: "Fee Type", x: 24 },
      { label: "Currency", x: 120 },
      { label: "Amount", x: 186, align: "right" },
    ]);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    data.incomeByFeeType.forEach((item, index) => {
      if (y > 260) { doc.addPage(); y = 20; }
      const bg = index % 2 === 0 ? 245 : 255;
      doc.setFillColor(bg, 250, index % 2 === 0 ? 247 : 255);
      doc.rect(20, y - 4, 170, 8, "F");
      doc.text(item.feeType, 24, y + 1);
      doc.text(item.currency, 120, y + 1);
      doc.text(formatCurrencyPlain(item.amount, item.currency), 186, y + 1, { align: "right" });
      y += 8;
    });
    y += 6;
    y = addLine(doc, y);
  }

  if (data.expensesByCategory.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY_GREEN);
    doc.text("Expenses by Category", 20, y);
    y += 8;

    y = addTableHeader(doc, y, [
      { label: "Category", x: 24 },
      { label: "Currency", x: 120 },
      { label: "Amount", x: 186, align: "right" },
    ]);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    data.expensesByCategory.forEach((item, index) => {
      if (y > 260) { doc.addPage(); y = 20; }
      const bg = index % 2 === 0 ? 245 : 255;
      doc.setFillColor(bg, 250, index % 2 === 0 ? 247 : 255);
      doc.rect(20, y - 4, 170, 8, "F");
      doc.text(item.category, 24, y + 1);
      doc.text(item.currency, 120, y + 1);
      doc.text(formatCurrencyPlain(item.amount, item.currency), 186, y + 1, { align: "right" });
      y += 8;
    });
  }

  addFooter(doc, branding);
  doc.save(`financial-report-${data.period}-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ─── Master Payment Report ───────────────────────────────────────────────────

export interface MasterPaymentRow {
  studentName: string;
  studentAdmissionNumber: string;
  studentClassGrade: string;
  receiptNumber: string;
  feeType: string;
  amount: number;
  currency: string;
  paymentDate: string;
  term: string;
}

export function generateMasterPaymentPDF(
  payments: MasterPaymentRow[],
  filters: { term?: string; classGrade?: string },
  branding?: BrandingParam
): void {
  const doc = new jsPDF({ orientation: "landscape" });
  let y = addHeader(doc, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const parts: string[] = ["Master Payment Report"];
  if (filters.term) parts.push(`— ${filters.term}`);
  if (filters.classGrade) parts.push(`— ${filters.classGrade}`);
  doc.text(parts.join(" "), 148.5, y, { align: "center" });
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  |  ${payments.length} record(s)`, 148.5, y, { align: "center" });
  y += 8;
  y = addLine(doc, y);

  const cols = [
    { label: "Student Name", x: 15, w: 55 },
    { label: "Adm. No.", x: 70, w: 25 },
    { label: "Class", x: 95, w: 25 },
    { label: "Receipt #", x: 120, w: 30 },
    { label: "Fee Type", x: 150, w: 35 },
    { label: "Term", x: 185, w: 25 },
    { label: "Date", x: 210, w: 30 },
    { label: "Amount", x: 240, w: 42 },
  ];

  doc.setFillColor(...PRIMARY_GREEN);
  doc.rect(10, y - 4, 277, 9, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  cols.forEach(c => doc.text(c.label, c.x, y + 2));
  y += 13;

  const totals: Record<string, number> = {};

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(40, 40, 40);

  payments.forEach((p, i) => {
    if (y > 190) { doc.addPage(); y = 20; }
    const bg = i % 2 === 0 ? 245 : 255;
    doc.setFillColor(bg, 250, i % 2 === 0 ? 247 : 255);
    doc.rect(10, y - 4, 277, 8, "F");
    doc.text((p.studentName || "").substring(0, 30), cols[0].x, y + 1);
    doc.text((p.studentAdmissionNumber || "").substring(0, 12), cols[1].x, y + 1);
    doc.text((p.studentClassGrade || "").substring(0, 12), cols[2].x, y + 1);
    doc.text((p.receiptNumber || "").substring(0, 14), cols[3].x, y + 1);
    doc.text((p.feeType || "").substring(0, 18), cols[4].x, y + 1);
    doc.text((p.term || "").substring(0, 10), cols[5].x, y + 1);
    const dateStr = p.paymentDate ? new Date(p.paymentDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "2-digit" }) : "";
    doc.text(dateStr, cols[6].x, y + 1);
    doc.text(formatCurrencyPlain(p.amount, p.currency), cols[7].x, y + 1);
    y += 8;
    totals[p.currency] = (totals[p.currency] || 0) + p.amount;
  });

  y += 4;
  y = addLine(doc, y);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Totals:", 15, y);
  y += 7;
  Object.entries(totals).forEach(([cur, total]) => {
    doc.setFontSize(9);
    doc.text(`${cur}: ${formatCurrencyPlain(total, cur)}`, 25, y);
    y += 6;
  });

  addFooter(doc, branding);
  doc.save(`master-payment-report-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ─── Payslip PDF ─────────────────────────────────────────────────────────────

export interface PayslipData {
  staffName: string;
  staffType: string;
  position?: string;
  subjects?: string[];
  month: string;
  baseSalary: number;
  accommodationAllowance: number;
  transportAllowance: number;
  otherAllowances: number;
  deductions: number;
  deductionNotes?: string;
  currency: string;
  status: string;
}

export function generatePayslipPDF(data: PayslipData, branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("PAYSLIP", 105, y, { align: "center" });
  y += 7;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Month: ${data.month}`, 105, y, { align: "center" });
  y += 10;
  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Employee Details", 20, y);
  y += 8;

  const addRow = (label: string, value: string) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(label, 25, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40, 40, 40);
    doc.text(value, 90, y);
    y += 7;
  };

  addRow("Name:", data.staffName);
  addRow("Staff Type:", data.staffType === "teacher" ? "Teaching Staff" : "Non-Teaching Staff");
  if (data.position) addRow("Position:", data.position);
  if (data.subjects && data.subjects.length > 0) addRow("Subjects:", data.subjects.join(", "));
  addRow("Status:", data.status);
  y += 4;
  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Earnings", 20, y);
  y += 8;

  const addAmountRow = (label: string, amount: number, isTotal = false) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", isTotal ? "bold" : "normal");
    doc.setTextColor(isTotal ? 40 : 80, isTotal ? 40 : 80, isTotal ? 40 : 80);
    doc.text(label, 25, y);
    doc.setFont("helvetica", "bold");
    doc.text(formatCurrencyPlain(amount, data.currency), 186, y, { align: "right" });
    y += 7;
  };

  addAmountRow("Base Salary", data.baseSalary);
  if (data.accommodationAllowance > 0) addAmountRow("Accommodation Allowance", data.accommodationAllowance);
  if (data.transportAllowance > 0) addAmountRow("Transport Allowance", data.transportAllowance);
  if (data.otherAllowances > 0) addAmountRow("Other Allowances", data.otherAllowances);

  const grossPay = data.baseSalary + data.accommodationAllowance + data.transportAllowance + data.otherAllowances;
  y += 2;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(25, y, 186, y);
  y += 5;
  addAmountRow("Gross Pay", grossPay, true);
  y += 4;

  if (data.deductions > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY_GREEN);
    doc.text("Deductions", 20, y);
    y += 8;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(220, 38, 38);
    doc.text(data.deductionNotes || "Deductions", 25, y);
    doc.setFont("helvetica", "bold");
    doc.text(`-${formatCurrencyPlain(data.deductions, data.currency)}`, 186, y, { align: "right" });
    y += 10;
  }

  y = addLine(doc, y);

  const netPay = grossPay - data.deductions;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Net Pay:", 25, y);
  doc.text(formatCurrencyPlain(netPay, data.currency), 186, y, { align: "right" });

  addFooter(doc, branding);
  doc.save(`payslip-${data.staffName.replace(/\s+/g, "-")}-${data.month}-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ─── Dividend Distribution Report ────────────────────────────────────────────

export interface DividendReportData {
  netProfit: number;
  currency: string;
  term: string;
  academicYear: string;
  payouts: { shareholderName: string; sharePercentage: string; payoutAmount: number }[];
  totalAllocated: number;
  retainedEarnings: number;
}

export function generateDividendReportPDF(data: DividendReportData, branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Dividend Distribution Report", 105, y, { align: "center" });
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`${data.term} · Academic Year ${data.academicYear} · ${data.currency}`, 105, y, { align: "center" });
  y += 4;
  doc.text(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 105, y, { align: "center" });
  y += 10;
  y = addLine(doc, y);

  doc.setFillColor(...PALE_MINT);
  doc.roundedRect(20, y, 170, 28, 4, 4, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Net Profit (Total Revenue - Total Expenses)", 105, y + 8, { align: "center" });
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(formatCurrencyPlain(data.netProfit, data.currency), 105, y + 20, { align: "center" });
  y += 36;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Shareholder Payouts", 20, y);
  y += 8;

  y = addTableHeader(doc, y, [
    { label: "Shareholder", x: 25 },
    { label: "Share %", x: 110, align: "right" },
    { label: "Dividend Amount", x: 186, align: "right" },
  ]);

  data.payouts.forEach((payout, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(245, 250, 247);
      doc.rect(20, y - 4, 170, 10, "F");
    }
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(payout.shareholderName, 25, y + 2);
    doc.text(`${parseFloat(payout.sharePercentage).toFixed(2)}%`, 110, y + 2, { align: "right" });
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY_GREEN);
    doc.text(formatCurrencyPlain(payout.payoutAmount, data.currency), 186, y + 2, { align: "right" });
    y += 10;
  });

  y = addLine(doc, y);

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Total Allocated:", 25, y);
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text(formatCurrencyPlain(data.totalAllocated, data.currency), 186, y, { align: "right" });
  y += 10;

  if (data.retainedEarnings > 0) {
    doc.setFillColor(255, 249, 231);
    doc.roundedRect(20, y, 170, 18, 3, 3, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text("Retained Earnings (Unallocated profit)", 25, y + 6);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(180, 120, 0);
    doc.text(formatCurrencyPlain(data.retainedEarnings, data.currency), 186, y + 12, { align: "right" });
    y += 26;
  }

  y += 4;
  doc.setFillColor(...PRIMARY_GREEN);
  doc.roundedRect(20, y, 170, 18, 3, 3, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 255, 255);
  doc.text("Net Profit", 25, y + 6);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(formatCurrencyPlain(data.netProfit, data.currency), 186, y + 12, { align: "right" });

  addFooter(doc, branding);
  doc.save(`dividend-report-${data.term.replace(/\s/g, "-")}-${data.academicYear.replace("/", "-")}-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ─── Detailed Expense Report ──────────────────────────────────────────────────

export interface DetailedExpenseRow {
  expenseDate: string | null;
  category: string;
  description: string;
  recordedBy: string;
  amount: number;
  currency: string;
  term?: string;
}

export function generateDetailedExpenseReportPDF(
  expenses: DetailedExpenseRow[],
  filters: { term?: string; currency?: string },
  branding?: BrandingParam
): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Detailed Expense Report", 105, y, { align: "center" });
  y += 7;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const filterParts: string[] = [];
  if (filters.term) filterParts.push(filters.term);
  if (filters.currency) filterParts.push(filters.currency);
  if (filterParts.length) doc.text(filterParts.join(" · "), 105, y, { align: "center" });
  y += 4;
  doc.text(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  ·  ${expenses.length} transaction(s)`, 105, y, { align: "center" });
  y += 10;
  y = addLine(doc, y);

  y = addTableHeader(doc, y, [
    { label: "Date", x: 22 },
    { label: "Category", x: 52 },
    { label: "Description", x: 92 },
    { label: "Recorded By", x: 148 },
    { label: "Amount", x: 186, align: "right" },
  ]);

  const categoryTotals: Record<string, Record<string, number>> = {};

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);

  expenses.forEach((exp, idx) => {
    if (y > 265) { doc.addPage(); y = 20; }
    const bg = idx % 2 === 0 ? 245 : 255;
    doc.setFillColor(bg, 250, idx % 2 === 0 ? 247 : 255);
    doc.rect(20, y - 3, 170, 8, "F");

    const dateStr = exp.expenseDate
      ? new Date(exp.expenseDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "2-digit" })
      : "N/A";

    doc.setTextColor(80, 80, 80);
    doc.text(dateStr, 22, y + 2);
    doc.text(exp.category.substring(0, 14), 52, y + 2);
    doc.text(exp.description.substring(0, 26), 92, y + 2);
    doc.text((exp.recordedBy || "—").substring(0, 16), 148, y + 2);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY_GREEN);
    doc.text(formatCurrencyPlain(exp.amount, exp.currency), 186, y + 2, { align: "right" });
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    y += 8;

    const key = `${exp.category}__${exp.currency}`;
    if (!categoryTotals[key]) categoryTotals[key] = { amount: 0 };
    categoryTotals[key].amount += exp.amount;
  });

  y += 4;
  y = addLine(doc, y);

  if (y > 230) { doc.addPage(); y = 20; }
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Total Category Expenditure", 20, y);
  y += 8;

  y = addTableHeader(doc, y, [
    { label: "Category", x: 24 },
    { label: "Currency", x: 120 },
    { label: "Total", x: 186, align: "right" },
  ]);

  const categoryGroups = Object.entries(categoryTotals);
  categoryGroups.sort(([a], [b]) => a.localeCompare(b));

  let grandTotals: Record<string, number> = {};
  categoryGroups.forEach(([key, val], idx) => {
    const [cat, cur] = key.split("__");
    const bg = idx % 2 === 0 ? 245 : 255;
    doc.setFillColor(bg, 250, idx % 2 === 0 ? 247 : 255);
    doc.rect(20, y - 3, 170, 8, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(cat, 24, y + 2);
    doc.text(cur, 120, y + 2);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY_GREEN);
    doc.text(formatCurrencyPlain(val.amount, cur), 186, y + 2, { align: "right" });
    grandTotals[cur] = (grandTotals[cur] || 0) + val.amount;
    y += 8;
  });

  y += 4;
  y = addLine(doc, y);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Grand Total:", 24, y);
  let totalX = y;
  Object.entries(grandTotals).forEach(([cur, amt]) => {
    doc.text(`${cur}: ${formatCurrencyPlain(amt, cur)}`, 80, totalX);
    totalX += 7;
  });

  addFooter(doc, branding);
  doc.save(`detailed-expense-report-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ─── Detailed Budget Report ───────────────────────────────────────────────────

export interface BudgetComparisonRow {
  category: string;
  estimated: number;
  actual: number;
  variance: number;
  status: string;
  currency: string;
}

export function generateDetailedBudgetReportPDF(
  comparison: BudgetComparisonRow[],
  meta: { term: string; academicYear: string },
  branding?: BrandingParam
): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Budget vs Actual Report", 105, y, { align: "center" });
  y += 7;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`${meta.term} · Academic Year ${meta.academicYear}`, 105, y, { align: "center" });
  y += 4;
  doc.text(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 105, y, { align: "center" });
  y += 10;
  y = addLine(doc, y);

  y = addTableHeader(doc, y, [
    { label: "Category", x: 22 },
    { label: "Currency", x: 75 },
    { label: "Estimated", x: 108, align: "right" },
    { label: "Actual", x: 140, align: "right" },
    { label: "Variance", x: 168, align: "right" },
    { label: "Utilization", x: 186, align: "right" },
  ]);

  let overBudget = 0, underBudget = 0;
  const currencyTotals: Record<string, { estimated: number; actual: number }> = {};

  comparison.forEach((row, idx) => {
    if (y > 265) { doc.addPage(); y = 20; }
    const utilization = row.estimated > 0 ? Math.round((row.actual / row.estimated) * 100) : 0;
    const isOver = row.status === "Over Budget";
    if (isOver) overBudget++;
    else underBudget++;

    const bg = idx % 2 === 0 ? 245 : 255;
    doc.setFillColor(bg, 250, idx % 2 === 0 ? 247 : 255);
    doc.rect(20, y - 3, 170, 8, "F");

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(row.category.substring(0, 18), 22, y + 2);
    doc.text(row.currency, 75, y + 2);
    doc.text(formatCurrencyPlain(row.estimated, row.currency), 108, y + 2, { align: "right" });
    doc.text(formatCurrencyPlain(row.actual, row.currency), 140, y + 2, { align: "right" });

    // Variance: positive = under budget (saved), negative = over budget
    const varianceAmt = row.estimated - row.actual; // positive = under budget
    doc.setFont("helvetica", "bold");
    doc.setTextColor(varianceAmt >= 0 ? 27 : 220, varianceAmt >= 0 ? 163 : 38, varianceAmt >= 0 ? 74 : 38);
    doc.text(`${varianceAmt >= 0 ? "+" : ""}${formatCurrencyPlain(Math.abs(row.variance), row.currency)}`, 168, y + 2, { align: "right" });

    // Utilization %
    const utilColor = utilization > 100 ? [220, 38, 38] : utilization > 85 ? [245, 158, 11] : [27, 67, 50];
    doc.setTextColor(utilColor[0], utilColor[1], utilColor[2]);
    doc.text(`${utilization}%`, 186, y + 2, { align: "right" });
    doc.setFont("helvetica", "normal");
    y += 8;

    if (!currencyTotals[row.currency]) currencyTotals[row.currency] = { estimated: 0, actual: 0 };
    currencyTotals[row.currency].estimated += row.estimated;
    currencyTotals[row.currency].actual += row.actual;
  });

  y += 4;
  y = addLine(doc, y);

  // Summary row
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY_GREEN);
  doc.text("Totals by Currency:", 22, y);
  y += 8;

  Object.entries(currencyTotals).forEach(([cur, totals]) => {
    if (y > 265) { doc.addPage(); y = 20; }
    const overallUtil = totals.estimated > 0 ? Math.round((totals.actual / totals.estimated) * 100) : 0;
    doc.setFillColor(...PALE_MINT);
    doc.roundedRect(20, y, 170, 14, 2, 2, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(cur, 25, y + 9);
    doc.setFont("helvetica", "bold");
    doc.text(`Budget: ${formatCurrencyPlain(totals.estimated, cur)}`, 50, y + 9);
    doc.text(`Actual: ${formatCurrencyPlain(totals.actual, cur)}`, 110, y + 9);
    const utilizationColor = overallUtil > 100 ? [220, 38, 38] : [27, 67, 50];
    doc.setTextColor(utilizationColor[0], utilizationColor[1], utilizationColor[2]);
    doc.text(`${overallUtil}% utilized`, 165, y + 9, { align: "right" });
    y += 20;
  });

  y += 4;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Categories under budget: ${underBudget}  ·  Categories over budget: ${overBudget}`, 105, y, { align: "center" });

  addFooter(doc, branding);
  doc.save(`budget-report-${meta.term.replace(/\s/g, "-")}-${meta.academicYear.replace("/", "-")}-${new Date().toISOString().split("T")[0]}.pdf`);
}
