import jsPDF from "jspdf";
import type { BrandingParam } from "./pdf-receipts";

function formatCurrencyPlain(amount: number, currency: string = "UGX"): string {
  const locale = currency === "USD" ? "en-US" : "en-UG";
  const formatter = new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: currency === "USD" ? 2 : 0,
    maximumFractionDigits: currency === "USD" ? 2 : 0,
  });
  return formatter.format(amount);
}

function addHeader(doc: jsPDF, branding?: BrandingParam): number {
  const schoolName = branding?.schoolName || "HelioPay System";
  const schoolAddress = branding?.schoolAddress || "";

  doc.setFillColor(15, 23, 42);
  const headerHeight = schoolAddress ? 45 : 40;
  doc.rect(0, 0, 210, headerHeight, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(schoolName, 105, 18, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  if (schoolAddress) {
    doc.text(schoolAddress, 105, 27, { align: "center" });
    doc.text("Financial Report", 105, 35, { align: "center" });
  } else {
    doc.text("Financial Report", 105, 27, { align: "center" });
  }

  doc.setTextColor(0, 0, 0);
  return headerHeight + 10;
}

function addLine(doc: jsPDF, y: number): number {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);
  return y + 6;
}

function addFooter(doc: jsPDF, branding?: BrandingParam): void {
  const schoolName = branding?.schoolName || "HelioPay System";
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(`Generated by ${schoolName} on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 105, pageHeight - 10, { align: "center" });
}

export interface FinancialSummary {
  totalIncome: { UGX: number; USD: number };
  totalExpenses: { UGX: number; USD: number };
  netBalance: { UGX: number; USD: number };
  expensesByCategory: { category: string; amount: number; currency: string }[];
  incomeByFeeType: { feeType: string; amount: number; currency: string }[];
  period: string;
  startDate: string;
  endDate: string;
}

export function generateFinancialReportPDF(data: FinancialSummary, branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const periodLabel = data.period === "weekly" ? "Weekly" : data.period === "monthly" ? "Monthly" : "Termly";
  doc.text(`${periodLabel} Financial Report`, 105, y, { align: "center" });
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const start = new Date(data.startDate).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  const end = new Date(data.endDate).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  doc.text(`Period: ${start} - ${end}`, 105, y, { align: "center" });
  y += 10;

  y = addLine(doc, y);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Financial Summary", 20, y);
  y += 10;

  const colLeft = 20;
  const colRight = 110;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Income (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text(formatCurrencyPlain(data.totalIncome.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Income (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text(formatCurrencyPlain(data.totalIncome.USD, "USD"), colRight, y + 5);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Expenses (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text(formatCurrencyPlain(data.totalExpenses.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Expenses (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text(formatCurrencyPlain(data.totalExpenses.USD, "USD"), colRight, y + 5);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Net Balance (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(data.netBalance.UGX >= 0 ? 22 : 220, data.netBalance.UGX >= 0 ? 163 : 38, data.netBalance.UGX >= 0 ? 74 : 38);
  doc.text(formatCurrencyPlain(data.netBalance.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Net Balance (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(data.netBalance.USD >= 0 ? 22 : 220, data.netBalance.USD >= 0 ? 163 : 38, data.netBalance.USD >= 0 ? 74 : 38);
  doc.text(formatCurrencyPlain(data.netBalance.USD, "USD"), colRight, y + 5);
  y += 16;

  y = addLine(doc, y);

  if (data.incomeByFeeType.length > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Income by Fee Type", 20, y);
    y += 8;

    doc.setFillColor(241, 245, 249);
    doc.rect(20, y, 170, 8, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Fee Type", 24, y + 5.5);
    doc.text("Currency", 120, y + 5.5);
    doc.text("Amount", 186, y + 5.5, { align: "right" });
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    data.incomeByFeeType.forEach((item, index) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      const bgColor = index % 2 === 0 ? 255 : 248;
      doc.setFillColor(bgColor, bgColor, bgColor);
      doc.rect(20, y - 4, 170, 8, "F");
      doc.text(item.feeType, 24, y + 1);
      doc.text(item.currency, 120, y + 1);
      doc.text(formatCurrencyPlain(item.amount, item.currency), 186, y + 1, { align: "right" });
      y += 8;
    });
    y += 6;
    y = addLine(doc, y);
  }

  if (data.expensesByCategory.length > 0) {
    if (y > 220) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Expenses by Category", 20, y);
    y += 8;

    doc.setFillColor(241, 245, 249);
    doc.rect(20, y, 170, 8, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Category", 24, y + 5.5);
    doc.text("Currency", 120, y + 5.5);
    doc.text("Amount", 186, y + 5.5, { align: "right" });
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    data.expensesByCategory.forEach((item, index) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      const bgColor = index % 2 === 0 ? 255 : 248;
      doc.setFillColor(bgColor, bgColor, bgColor);
      doc.rect(20, y - 4, 170, 8, "F");
      doc.text(item.category, 24, y + 1);
      doc.text(item.currency, 120, y + 1);
      doc.text(formatCurrencyPlain(item.amount, item.currency), 186, y + 1, { align: "right" });
      y += 8;
    });
  }

  addFooter(doc, branding);
  doc.save(`financial-report-${data.period}-${new Date().toISOString().split("T")[0]}.pdf`);
}

export interface MasterPaymentRow {
  studentName: string;
  studentAdmissionNumber: string;
  studentClassGrade: string;
  receiptNumber: string;
  feeType: string;
  amount: number;
  currency: string;
  paymentDate: string;
  term: string;
}

export function generateMasterPaymentPDF(
  payments: MasterPaymentRow[],
  filters: { term?: string; classGrade?: string },
  branding?: BrandingParam
): void {
  const doc = new jsPDF({ orientation: "landscape" });
  let y = addHeader(doc, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const parts: string[] = ["Master Payment Report"];
  if (filters.term) parts.push(`— ${filters.term}`);
  if (filters.classGrade) parts.push(`— ${filters.classGrade}`);
  doc.text(parts.join(" "), 148.5, y, { align: "center" });
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  |  ${payments.length} record(s)`, 148.5, y, { align: "center" });
  y += 8;
  y = addLine(doc, y);

  const cols = [
    { label: "Student Name", x: 15, w: 55 },
    { label: "Adm. No.", x: 70, w: 25 },
    { label: "Class", x: 95, w: 25 },
    { label: "Receipt #", x: 120, w: 30 },
    { label: "Fee Type", x: 150, w: 35 },
    { label: "Term", x: 185, w: 25 },
    { label: "Date", x: 210, w: 30 },
    { label: "Amount", x: 240, w: 42 },
  ];

  doc.setFillColor(241, 245, 249);
  doc.rect(10, y - 4, 277, 8, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  cols.forEach(c => doc.text(c.label, c.x, y + 1));
  y += 10;

  const totals: Record<string, number> = {};

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(40, 40, 40);

  payments.forEach((p, i) => {
    if (y > 190) {
      doc.addPage();
      y = 20;
    }
    const bg = i % 2 === 0 ? 255 : 248;
    doc.setFillColor(bg, bg, bg);
    doc.rect(10, y - 4, 277, 8, "F");
    doc.text((p.studentName || "").substring(0, 30), cols[0].x, y + 1);
    doc.text((p.studentAdmissionNumber || "").substring(0, 12), cols[1].x, y + 1);
    doc.text((p.studentClassGrade || "").substring(0, 12), cols[2].x, y + 1);
    doc.text((p.receiptNumber || "").substring(0, 14), cols[3].x, y + 1);
    doc.text((p.feeType || "").substring(0, 18), cols[4].x, y + 1);
    doc.text((p.term || "").substring(0, 10), cols[5].x, y + 1);
    const dateStr = p.paymentDate ? new Date(p.paymentDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "2-digit" }) : "";
    doc.text(dateStr, cols[6].x, y + 1);
    doc.text(formatCurrencyPlain(p.amount, p.currency), cols[7].x, y + 1);
    y += 8;

    totals[p.currency] = (totals[p.currency] || 0) + p.amount;
  });

  y += 4;
  y = addLine(doc, y);

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Totals:", 15, y);
  y += 7;
  Object.entries(totals).forEach(([cur, total]) => {
    doc.setFontSize(9);
    doc.text(`${cur}: ${formatCurrencyPlain(total, cur)}`, 25, y);
    y += 6;
  });

  const pageHeight = doc.internal.pageSize.getHeight();
  const schoolName = branding?.schoolName || "HelioPay System";
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(`Generated by ${schoolName}`, 148.5, pageHeight - 10, { align: "center" });

  doc.save(`master-payment-report-${new Date().toISOString().split("T")[0]}.pdf`);
}

export interface PayslipData {
  staffName: string;
  staffType: string;
  position?: string;
  subjects?: string[];
  month: string;
  baseSalary: number;
  accommodationAllowance: number;
  transportAllowance: number;
  otherAllowances: number;
  deductions: number;
  deductionNotes?: string;
  currency: string;
  status: string;
}

export function generatePayslipPDF(data: PayslipData, branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("PAYSLIP", 105, y, { align: "center" });
  y += 7;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Month: ${data.month}`, 105, y, { align: "center" });
  y += 10;
  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Employee Details", 20, y);
  y += 8;

  const addRow = (label: string, value: string) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(label, 25, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40, 40, 40);
    doc.text(value, 90, y);
    y += 7;
  };

  addRow("Name:", data.staffName);
  addRow("Staff Type:", data.staffType === "teacher" ? "Teaching Staff" : "Non-Teaching Staff");
  if (data.position) addRow("Position:", data.position);
  if (data.subjects && data.subjects.length > 0) addRow("Subjects:", data.subjects.join(", "));
  addRow("Status:", data.status);
  y += 4;
  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Earnings", 20, y);
  y += 8;

  const addAmountRow = (label: string, amount: number, isTotal = false) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", isTotal ? "bold" : "normal");
    doc.setTextColor(isTotal ? 40 : 80, isTotal ? 40 : 80, isTotal ? 40 : 80);
    doc.text(label, 25, y);
    doc.setFont("helvetica", "bold");
    doc.text(formatCurrencyPlain(amount, data.currency), 186, y, { align: "right" });
    y += 7;
  };

  addAmountRow("Base Salary", data.baseSalary);
  if (data.accommodationAllowance > 0) addAmountRow("Accommodation Allowance", data.accommodationAllowance);
  if (data.transportAllowance > 0) addAmountRow("Transport Allowance", data.transportAllowance);
  if (data.otherAllowances > 0) addAmountRow("Other Allowances", data.otherAllowances);

  const grossPay = data.baseSalary + data.accommodationAllowance + data.transportAllowance + data.otherAllowances;
  y += 2;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(25, y, 186, y);
  y += 5;
  addAmountRow("Gross Pay", grossPay, true);
  y += 4;

  if (data.deductions > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Deductions", 20, y);
    y += 8;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(220, 38, 38);
    doc.text(data.deductionNotes || "Deductions", 25, y);
    doc.setFont("helvetica", "bold");
    doc.text(`-${formatCurrencyPlain(data.deductions, data.currency)}`, 186, y, { align: "right" });
    y += 10;
  }

  y = addLine(doc, y);

  const netPay = grossPay - data.deductions;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text("Net Pay:", 25, y);
  doc.text(formatCurrencyPlain(netPay, data.currency), 186, y, { align: "right" });

  addFooter(doc, branding);
  doc.save(`payslip-${data.staffName.replace(/\s+/g, "-")}-${data.month}-${new Date().toISOString().split("T")[0]}.pdf`);
}
