import jsPDF from "jspdf";
import QRCode from "qrcode";
import type { BrandingSettings } from "@shared/schema";

export type BrandingParam = Pick<BrandingSettings, "schoolName" | "schoolAddress"> | null | undefined;

function formatCurrencyPlain(amount: number, currency: string = "UGX"): string {
  const locale = currency === "USD" ? "en-US" : "en-UG";
  const formatter = new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: currency === "USD" ? 2 : 0,
    maximumFractionDigits: currency === "USD" ? 2 : 0,
  });
  return formatter.format(amount);
}

function addHeader(doc: jsPDF, y: number, branding?: BrandingParam): number {
  const schoolName = branding?.schoolName || "HelioPay System";
  const schoolAddress = branding?.schoolAddress || "";

  doc.setFillColor(15, 23, 42);
  const headerHeight = schoolAddress ? 45 : 40;
  doc.rect(0, 0, 210, headerHeight, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(schoolName, 105, 18, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  if (schoolAddress) {
    doc.text(schoolAddress, 105, 27, { align: "center" });
    doc.text("School Financial Management", 105, 35, { align: "center" });
  } else {
    doc.text("School Financial Management", 105, 27, { align: "center" });
  }

  doc.setTextColor(0, 0, 0);
  return headerHeight + 10;
}

function addLine(doc: jsPDF, y: number): number {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);
  return y + 6;
}

function addLabelValue(doc: jsPDF, label: string, value: string, y: number, x: number = 20): number {
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(label, x, y);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text(value, x, y + 5);
  return y + 14;
}

function addSignatureLine(doc: jsPDF, y: number): void {
  y += 10;
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(20, y + 20, 90, y + 20);
  doc.line(120, y + 20, 190, y + 20);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Authorized Signature", 55, y + 26, { align: "center" });
  doc.text("Date / Stamp", 155, y + 26, { align: "center" });
}

function addFooter(doc: jsPDF, branding?: BrandingParam): void {
  const schoolName = branding?.schoolName || "HelioPay System";
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(`Generated by ${schoolName}`, 105, pageHeight - 10, { align: "center" });
}

export async function generatePaymentReceiptPDF(payment: any, student: any, branding?: BrandingParam): Promise<void> {
  const doc = new jsPDF();
  let y = addHeader(doc, 0, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Official Payment Receipt", 105, y, { align: "center" });
  y += 10;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Receipt No: ${payment.receiptNumber || "N/A"}`, 105, y, { align: "center" });
  y += 10;

  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Student Information", 20, y);
  y += 8;

  const leftX = 20;
  const rightX = 110;

  y = addLabelValue(doc, "Student Name", student?.fullName || "N/A", y, leftX);
  const savedY = y - 14;
  addLabelValue(doc, "Admission No.", student?.admissionNumber || "N/A", savedY, rightX);

  y = addLabelValue(doc, "Class / Grade", student?.classGrade || "N/A", y, leftX);
  const savedY2 = y - 14;
  addLabelValue(doc, "Academic Year", student?.academicYear || "N/A", savedY2, rightX);

  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Payment Details", 20, y);
  y += 8;

  const paymentDate = payment.paymentDate
    ? new Date(payment.paymentDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : "N/A";

  y = addLabelValue(doc, "Payment Date", paymentDate, y, leftX);
  const savedY3 = y - 14;
  addLabelValue(doc, "Term", payment.term || "N/A", savedY3, rightX);

  y = addLabelValue(doc, "Fee Type", payment.feeType || "N/A", y, leftX);
  const savedY4 = y - 14;
  addLabelValue(doc, "Recorded By", payment.recordedBy || "N/A", savedY4, rightX);

  if (payment.notes) {
    y = addLabelValue(doc, "Notes", payment.notes, y, leftX);
  }

  y += 4;
  y = addLine(doc, y);

  doc.setFillColor(240, 253, 244);
  doc.roundedRect(20, y, 170, 28, 3, 3, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Amount Received", 105, y + 10, { align: "center" });
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text(formatCurrencyPlain(payment.amount, payment.currency), 105, y + 22, { align: "center" });

  y += 36;

  try {
    const baseUrl = window.location.origin;
    const verifyUrl = `${baseUrl}/verify/receipt/${encodeURIComponent(payment.receiptNumber || "")}`;
    const qrDataUrl = await QRCode.toDataURL(verifyUrl, { width: 120, margin: 1, errorCorrectionLevel: "M" });
    const qrSize = 32;
    const qrX = 155;
    doc.addImage(qrDataUrl, "PNG", qrX, y, qrSize, qrSize);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text("Scan to verify", qrX + qrSize / 2, y + qrSize + 4, { align: "center" });
  } catch {}

  addSignatureLine(doc, y);
  addFooter(doc, branding);

  doc.save(`receipt-${payment.receiptNumber || payment.id}.pdf`);
}

export function generateExpenseReceiptPDF(expense: any, branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, 0, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Expense Voucher", 105, y, { align: "center" });
  y += 10;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Voucher No: EXP-${String(expense.id).padStart(5, "0")}`, 105, y, { align: "center" });
  y += 10;

  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Expense Details", 20, y);
  y += 8;

  const leftX = 20;
  const rightX = 110;

  const expenseDate = expense.expenseDate
    ? new Date(expense.expenseDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : "N/A";

  y = addLabelValue(doc, "Date", expenseDate, y, leftX);
  const savedY = y - 14;
  addLabelValue(doc, "Category", expense.category || "N/A", savedY, rightX);

  y = addLabelValue(doc, "Recorded By", expense.recordedBy || "N/A", y, leftX);

  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Description", 20, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  const descLines = doc.splitTextToSize(expense.description || "N/A", 170);
  doc.text(descLines, 20, y);
  y += descLines.length * 5 + 8;

  y = addLine(doc, y);

  doc.setFillColor(254, 242, 242);
  doc.roundedRect(20, y, 170, 28, 3, 3, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Amount Spent", 105, y + 10, { align: "center" });
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text(formatCurrencyPlain(expense.amount, expense.currency), 105, y + 22, { align: "center" });

  y += 36;

  addSignatureLine(doc, y);
  addFooter(doc, branding);

  doc.save(`expense-voucher-EXP-${String(expense.id).padStart(5, "0")}.pdf`);
}

export function generatePayrollReceiptPDF(payroll: any, items: any[], branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, 0, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Payroll Summary", 105, y, { align: "center" });
  y += 10;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Payroll ID: PAY-${String(payroll.id).padStart(5, "0")}`, 105, y, { align: "center" });
  y += 10;

  y = addLine(doc, y);

  const leftX = 20;
  const rightX = 110;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Payroll Information", 20, y);
  y += 8;

  y = addLabelValue(doc, "Month", payroll.month || "N/A", y, leftX);
  const savedY = y - 14;
  addLabelValue(doc, "Status", payroll.status || "N/A", savedY, rightX);

  y = addLabelValue(doc, "Created By", payroll.createdBy || "N/A", y, leftX);
  const savedY2 = y - 14;
  const createdDate = payroll.createdAt
    ? new Date(payroll.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : "N/A";
  addLabelValue(doc, "Created Date", createdDate, savedY2, rightX);

  if (payroll.approvedBy) {
    y = addLabelValue(doc, "Approved By", payroll.approvedBy, y, leftX);
    const savedY3 = y - 14;
    const approvedDate = payroll.approvedAt
      ? new Date(payroll.approvedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
      : "N/A";
    addLabelValue(doc, "Approved Date", approvedDate, savedY3, rightX);
  }

  y = addLine(doc, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Teacher Salary Breakdown", 20, y);
  y += 8;

  doc.setFillColor(241, 245, 249);
  doc.rect(20, y, 170, 8, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("#", 24, y + 5.5);
  doc.text("Teacher Name", 34, y + 5.5);
  doc.text("Amount", 186, y + 5.5, { align: "right" });
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(9);

  items.forEach((item, index) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    const bgColor = index % 2 === 0 ? 255 : 248;
    doc.setFillColor(bgColor, bgColor, bgColor);
    doc.rect(20, y - 4, 170, 8, "F");
    doc.text(String(index + 1), 24, y + 1);
    doc.text(item.teacherName || "Unknown", 34, y + 1);
    doc.text(formatCurrencyPlain(item.amount, item.currency || payroll.currency), 186, y + 1, { align: "right" });
    y += 8;
  });

  y += 2;
  doc.setDrawColor(60, 60, 60);
  doc.setLineWidth(0.5);
  doc.line(120, y, 190, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Total:", 120, y);
  doc.setTextColor(15, 23, 42);
  doc.text(formatCurrencyPlain(payroll.totalAmount, payroll.currency), 186, y, { align: "right" });

  y += 10;

  addSignatureLine(doc, y);
  addFooter(doc, branding);

  doc.save(`payroll-${payroll.month}-PAY-${String(payroll.id).padStart(5, "0")}.pdf`);
}
