import jsPDF from "jspdf";
import type { BrandingParam } from "./pdf-receipts";

function formatCurrencyPlain(amount: number, currency: string = "UGX"): string {
  const locale = currency === "USD" ? "en-US" : "en-UG";
  const formatter = new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    minimumFractionDigits: currency === "USD" ? 2 : 0,
    maximumFractionDigits: currency === "USD" ? 2 : 0,
  });
  return formatter.format(amount);
}

function addHeader(doc: jsPDF, branding?: BrandingParam): number {
  const schoolName = branding?.schoolName || "HelioPay System";
  const schoolAddress = branding?.schoolAddress || "";

  doc.setFillColor(15, 23, 42);
  const headerHeight = schoolAddress ? 45 : 40;
  doc.rect(0, 0, 210, headerHeight, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(schoolName, 105, 18, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  if (schoolAddress) {
    doc.text(schoolAddress, 105, 27, { align: "center" });
    doc.text("Financial Report", 105, 35, { align: "center" });
  } else {
    doc.text("Financial Report", 105, 27, { align: "center" });
  }

  doc.setTextColor(0, 0, 0);
  return headerHeight + 10;
}

function addLine(doc: jsPDF, y: number): number {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);
  return y + 6;
}

function addFooter(doc: jsPDF, branding?: BrandingParam): void {
  const schoolName = branding?.schoolName || "HelioPay System";
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(`Generated by ${schoolName} on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 105, pageHeight - 10, { align: "center" });
}

export interface FinancialSummary {
  totalIncome: { UGX: number; USD: number };
  totalExpenses: { UGX: number; USD: number };
  netBalance: { UGX: number; USD: number };
  expensesByCategory: { category: string; amount: number; currency: string }[];
  incomeByFeeType: { feeType: string; amount: number; currency: string }[];
  period: string;
  startDate: string;
  endDate: string;
}

export function generateFinancialReportPDF(data: FinancialSummary, branding?: BrandingParam): void {
  const doc = new jsPDF();
  let y = addHeader(doc, branding);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  const periodLabel = data.period === "weekly" ? "Weekly" : data.period === "monthly" ? "Monthly" : "Termly";
  doc.text(`${periodLabel} Financial Report`, 105, y, { align: "center" });
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const start = new Date(data.startDate).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  const end = new Date(data.endDate).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  doc.text(`Period: ${start} - ${end}`, 105, y, { align: "center" });
  y += 10;

  y = addLine(doc, y);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Financial Summary", 20, y);
  y += 10;

  const colLeft = 20;
  const colRight = 110;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Income (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text(formatCurrencyPlain(data.totalIncome.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Income (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(22, 163, 74);
  doc.text(formatCurrencyPlain(data.totalIncome.USD, "USD"), colRight, y + 5);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Expenses (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text(formatCurrencyPlain(data.totalExpenses.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Total Expenses (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text(formatCurrencyPlain(data.totalExpenses.USD, "USD"), colRight, y + 5);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Net Balance (UGX)", colLeft, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(data.netBalance.UGX >= 0 ? 22 : 220, data.netBalance.UGX >= 0 ? 163 : 38, data.netBalance.UGX >= 0 ? 74 : 38);
  doc.text(formatCurrencyPlain(data.netBalance.UGX, "UGX"), colLeft, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Net Balance (USD)", colRight, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(data.netBalance.USD >= 0 ? 22 : 220, data.netBalance.USD >= 0 ? 163 : 38, data.netBalance.USD >= 0 ? 74 : 38);
  doc.text(formatCurrencyPlain(data.netBalance.USD, "USD"), colRight, y + 5);
  y += 16;

  y = addLine(doc, y);

  if (data.incomeByFeeType.length > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Income by Fee Type", 20, y);
    y += 8;

    doc.setFillColor(241, 245, 249);
    doc.rect(20, y, 170, 8, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Fee Type", 24, y + 5.5);
    doc.text("Currency", 120, y + 5.5);
    doc.text("Amount", 186, y + 5.5, { align: "right" });
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    data.incomeByFeeType.forEach((item, index) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      const bgColor = index % 2 === 0 ? 255 : 248;
      doc.setFillColor(bgColor, bgColor, bgColor);
      doc.rect(20, y - 4, 170, 8, "F");
      doc.text(item.feeType, 24, y + 1);
      doc.text(item.currency, 120, y + 1);
      doc.text(formatCurrencyPlain(item.amount, item.currency), 186, y + 1, { align: "right" });
      y += 8;
    });
    y += 6;
    y = addLine(doc, y);
  }

  if (data.expensesByCategory.length > 0) {
    if (y > 220) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Expenses by Category", 20, y);
    y += 8;

    doc.setFillColor(241, 245, 249);
    doc.rect(20, y, 170, 8, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Category", 24, y + 5.5);
    doc.text("Currency", 120, y + 5.5);
    doc.text("Amount", 186, y + 5.5, { align: "right" });
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    data.expensesByCategory.forEach((item, index) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      const bgColor = index % 2 === 0 ? 255 : 248;
      doc.setFillColor(bgColor, bgColor, bgColor);
      doc.rect(20, y - 4, 170, 8, "F");
      doc.text(item.category, 24, y + 1);
      doc.text(item.currency, 120, y + 1);
      doc.text(formatCurrencyPlain(item.amount, item.currency), 186, y + 1, { align: "right" });
      y += 8;
    });
  }

  addFooter(doc, branding);
  doc.save(`financial-report-${data.period}-${new Date().toISOString().split("T")[0]}.pdf`);
}
